#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#

name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main # 'main' 分支
      - 'releases/*' # 发布分支

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # 检出实际的拉取请求 (Pull Request) 提交，而不是合并提交
          fetch-depth: 0  # 拉取请求分析需要完整的提交历史记录
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2026.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with: # 当 pr-mode 设置为 true 时，Qodana 仅分析已更改的文件
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          # 将 Qodana 结果（SARIF、其他产物、日志）作为构建产物上传到当前任务
          upload-result: false
          # 快速修复功能在 Ultimate 和 Ultimate Plus 订阅计划中可用
          push-fixes: 'none'